# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import MySQLdb

class Ui_MainWindow(object):
    def log_in(user, pas):
          pass

    def clicked(self):
        try:
            mydb = MySQLdb.connect(host='localhost', user=self.lineEdit.text(), passwd=self.lineEdit_2.text(), db='clients')
            cur = mydb.cursor()
            command = cur.execute('show tables')
            print("success",cur.fetchall()[0][0])
        except:
            print("error")
            self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"\n"
"border-color:rgb(255,0,0);\n"
"\n"
"border-style: solid;\n"
"  border-width: 1.5px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 2px;\n"
"transition:border-color 2s;\n"
"font-size: 16px;\n"
"background: rgba(0,0,0,0.0);\n"
"    color: rgb(239, 239, 239);\n"
"}\n"
"QLineEdit:hover{\n"
"border-color:rgb(200,0, 0);\n"
"}\n"
"\n"
"\n"
"")




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        MainWindow.setMinimumSize(QtCore.QSize(400, 600))
        MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/stamp 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(56, 61, 51);\n"
"border:0px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 149, 401, 471))
        self.frame.setStyleSheet("\n"
"background-image: url(:/newPrefix/Group 34.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")



        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(140, 260, 120, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 30))
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(69, 139, 100);\n"
"border-radius: 15px;\n"
" transition: width 2s;\n"
"    font: 57 11pt \"BoutrosMBCDinkum\";\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"   background-color:rgb(32, 255, 151);\n"
"    color: rgb(124, 142, 143);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(230, 222, 16, 17))
        self.checkBox.setStyleSheet("")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(155, 220, 71, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 10pt \"BoutrosMBCDinkum Medium\";\n"
"")
        self.pushButton.clicked.connect(self.clicked)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(75, 120, 250, 35))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"border-color:rgb(189, 189, 189);\n"
"\n"
"border-style: solid;\n"
"  border-width: 1.5px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 2px;\n"
"transition:border-color 2s;\n"
"font-size: 16px;\n"
"background: rgba(0,0,0,0.0);\n"
"    color: rgb(239, 239, 239);\n"
"}\n"
"QLineEdit:hover{\n"
"border-color:rgb(103, 103, 103);\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(75, 170, 250, 35))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"\n"
"border-color:rgb(189, 189, 189);\n"
"\n"
"border-style: solid;\n"
"  border-width: 1.5px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 2px;\n"
"transition:border-color 2s;\n"
"font-size: 16px;\n"
"background: rgba(0,0,0,0.0);\n"
"    color: rgb(239, 239, 239);\n"
"}\n"
"QLineEdit:hover{\n"
"border-color:rgb(103, 103, 103);\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(175, 300, 50, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(46, 79, 307, 61))
        self.frame_2.setStyleSheet("background-image: url(:/newPrefix/Group 32.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(150, -4, 100, 80))
        self.frame_3.setStyleSheet("image: url(:/newPrefix/logo shape.png);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Wad alkhalifa", "wad alkhalifa"))
        self.pushButton.setText(_translate("MainWindow", "تسجيل الدخول"))
        self.label.setText(_translate("MainWindow", "البقاء متصلا"))



import res_rc
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
